MechSoftExample/Models/MechSoftExample.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechSoftExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCMeetingExampleEntities2 : DbContext
    {
        public MVCMeetingExampleEntities2()
            : base("name=MVCMeetingExampleEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meeting> Meetings { get; set; }
    }
}

MechSoftExample/Models/MechSoftExample.Designer.cs
// T4 code generation is enabled for model 'C:\Users\berka\source\repos\MechSoftExample\MechSoftExample\Models\MechSoftExample.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MechSoftExample/Models/MechSoftExample.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MechSoftExample/Models/Meeting.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechSoftExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingID { get; set; }
        public string MeetingTopic { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public System.TimeSpan MeetingStartTime { get; set; }
        public System.TimeSpan MeetingEndTime { get; set; }
        public string Participant { get; set; }
    }
}

MechSoftExample/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MechSoftExample.Models;

namespace MechSoftExample.Controllers
{
    public class MeetingsController : Controller
    {
        private MVCMeetingExampleEntities2 db = new MVCMeetingExampleEntities2();

        // GET: Meetings
        public ActionResult Index()
        {
            var list = db.Meetings.ToList();
            return View(db.Meetings.ToList());
        }

        // GET: Meetings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meeting meeting = db.Meetings.Find(id);
            if (meeting == null)
            {
                return HttpNotFound();
            }
            return View(meeting);
        }

        // GET: Meetings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Meetings/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MeetingID,MeetingTopic,MeetingDate,MeetingStartTime,MeetingEndTime,Participant")] Meeting meeting)
        {
            if (ModelState.IsValid)
            {
                db.Meetings.Add(meeting);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(meeting);
        }

        // GET: Meetings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meeting meeting = db.Meetings.Find(id);
            if (meeting == null)
            {
                return HttpNotFound();
            }
            return View(meeting);
        }

        // POST: Meetings/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MeetingID,MeetingTopic,MeetingDate,MeetingStartTime,MeetingEndTime,Participant")] Meeting meeting)
        {
            if (ModelState.IsValid)
            {
                db.Entry(meeting).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(meeting);
        }

        // GET: Meetings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meeting meeting = db.Meetings.Find(id);
            if (meeting == null)
            {
                return HttpNotFound();
            }
            return View(meeting);
        }

        // POST: Meetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Meeting meeting = db.Meetings.Find(id);
            db.Meetings.Remove(meeting);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MechSoftExample/Views/Meetings/Create.cshtml
@using MechSoftExample.Models
@model Meeting

@{
    ViewBag.Title = "Create";
}

<script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker();
    });
</script>
<h2>Toplantı Oluştur</h2>

@using (@Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MeetingTopic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingTopic, new { htmlAttributes = new { @class = "form-control", Placeholder = "Lütfen toplantı başlığını giriniz.", Required = "" } })
                @Html.ValidationMessageFor(model => model.MeetingTopic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingDate, new { htmlAttributes = new { @type = "date", @class = "form-control ", Placeholder = "Lütfen toplantı tarihini giriniz." } })
                @*@Html.TextBoxFor(model => model.MeetingDate, new { @type = "date", @class = "form-control datepicker"})*@
                @*@Html.TextBoxFor(model => model.MeetingDate, String.Format("{0:MM/dd/yyyy}", new { id = "datepicker", @class = "form-control" }))*@
                @Html.ValidationMessageFor(model => model.MeetingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingStartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingStartTime, new { htmlAttributes = new { @type = "time", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingStartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingEndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingEndTime, new { htmlAttributes = new { @type = "time", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingEndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Participant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Participant, new { htmlAttributes = new { @class = "form-control", Placeholder = "Lütfen katılımcıları giriniz.", Required = "" } })
                @Html.ValidationMessageFor(model => model.Participant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Toplantı Listesine Git", "Index")
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Site.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

}

MechSoftExample/Views/Meetings/Delete.cshtml
@model MechSoftExample.Models.Meeting

@{
    ViewBag.Title = "Delete";
}

<h2>Toplantı Sil</h2>

<h3>Seçilen toplantıyı silmek istediğinizden emin misiniz?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MeetingTopic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingTopic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>

        <dd>
            @{string tarih = Model.MeetingDate.ToShortDateString();}
            @Html.DisplayFor(model => tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingStartTime)
        </dt>

        <dd>
            @{ string startTime = Model.MeetingStartTime.ToString(@"hh\:mm");}
            @Html.DisplayFor(model => startTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingEndTime)
        </dt>

        <dd>
            @{ string endTime = Model.MeetingEndTime.ToString(@"hh\:mm");}
            @Html.DisplayFor(model => endTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Participant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Participant)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Toplantı Listesine Git", "Index")
        </div>
    }
</div>

MechSoftExample/Views/Meetings/Details.cshtml
@model MechSoftExample.Models.Meeting

@{
    ViewBag.Title = "Details";
}

<h2>Toplantı Detayları</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MeetingTopic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingTopic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>

        <dd>
            @{string tarih = Model.MeetingDate.ToShortDateString();}
                @Html.DisplayFor(modelItem => tarih)
            </dd>

        <dt>            
            @Html.DisplayNameFor(model => model.MeetingStartTime)
        </dt>

        <dd>
            @{ string startTime = Model.MeetingStartTime.ToString(@"hh\:mm");}
            @Html.DisplayFor(model => startTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingEndTime)
        </dt>

        <dd>
            @{ string endTime = Model.MeetingEndTime.ToString(@"hh\:mm");}
            @Html.DisplayFor(model => endTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Participant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Participant)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Güncelle", "Edit", new { id = Model.MeetingID }) |
    @Html.ActionLink("Toplantı Listesine Git", "Index")
</p>

MechSoftExample/Views/Meetings/Edit.cshtml
@model MechSoftExample.Models.Meeting

@{
    ViewBag.Title = "Edit";
}

<h2>Toplantı Güncelle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MeetingID)

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingTopic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingTopic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingTopic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MeetingDate, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.TextBoxFor(model => model.MeetingDate, new { @type = "date", @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.MeetingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingStartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingStartTime, new { htmlAttributes = new { @type = "time", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingStartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingEndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingStartTime, new { htmlAttributes = new { @type = "time", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingEndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Participant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Participant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Participant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Güncelle" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Toplantı Listesine Git", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/Site.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datepicker]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+10"
            });

        });
    </script>
}

MechSoftExample/Views/Meetings/Index.cshtml
@model IEnumerable<MechSoftExample.Models.Meeting>

@{
    ViewBag.Title = "Index";
}

<h2>Toplantı Listesi</h2>

<p>
    @Html.ActionLink("Yeni Toplantı Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MeetingTopic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeetingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeetingStartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeetingEndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Participant)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MeetingTopic)
            </td>
            <td>
                @{string date = item.MeetingDate.ToShortDateString();}
                @Html.DisplayFor(modelItem => date)
            </td>
            <td>
                @{ string startTime = item.MeetingStartTime.ToString(@"hh\:mm");}
                @Html.DisplayFor(modelItem => startTime)
            </td>
            <td>
                @{ string endTime = item.MeetingEndTime.ToString(@"hh\:mm");}
                @Html.DisplayFor(modelItem => endTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Participant)
            </td>
            <td>
                @Html.ActionLink("Güncelle", "Edit", new { id = item.MeetingID }, new {@class="btn btn btn-success"}) |
                @Html.ActionLink("Detaylar", "Details", new { id = item.MeetingID },new { @class = "btn btn btn-info" }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.MeetingID }, new { @class = "btn btn btn-danger" })
            </td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/Site.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

MechSoftExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MechSoft", "Index", "Meetings", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Toplantı Oluştur", "Create", "Meetings")</li>
                    <li>@Html.ActionLink("Toplantı Listesi", "Index", "Meetings")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <script src="~/Scripts/jquery-3.2.1.js"></script>
        <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>
        <script src="~/Scripts/Site.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/Scripts/jquery-3.2.1.js"></script>
        <script src="~/Scripts/jquery-ui.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MechSoft Toplantı Oluşturma Otomasyonu</p>
        </footer>
    </div>
    
</body>
</html>